print("CADASTRO")
print("")
print("")
print("")
texto=input("qual seu nome?:")
print("seu nome é:" ,texto)
textoo=input("qual seu cpf?:")
print("seu cpf é:" ,textoo)
textooo=input("qual seu rg?:")
print("seu rg é:" ,textooo)