print("curso", "de" , "python" , sep="_" , end="%%") 
print("")
print("*no senai rio claro")
print("_-_-_logica" , "de" , "programação" , sep="_-_-_")
print("")
print("")
print("")
print("")
print("python" , "versao" , sep="@@@" , end="3[]")
print("")
print("logica" , "de" , "programação" , sep="###")
print("")
print("&uso" , "do" , "print", sep="&" , end="()")